name: devcontainer-base

on:
  push:
    branches: ["master"]
    paths:
      - "devcontainer/.devcontainer/**"
      - ".github/workflows/devcontainer-base.yaml"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the devcontainer base image
        run: |
          devcontainer build --image-name ghcr.io/exeteres/devcontainer-base:${{ env.GITHUB_SHA }} --workspace-folder . --push
        working-directory: devcontainer
