name: devcontainer

on:
  push:
    branches: ["master"]
    paths:
      - "devcontainer/**"
      - ".github/workflows/devcontainer.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: devcontainer

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Build devcontainer
        run: devcontainer build --image-name devcontainer --workspace-folder devcontainer --cache-from type=gha

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=

      - run: echo 'FROM devcontainer' > /tmp/Dockerfile
      - name: Label and push image
        uses: docker/build-push-action@v5
        with:
          context: devcontainer
          file: /tmp/Dockerfile
          push: true
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
