name: devcontainer

on:
  push:
    branches: ["master"]
    paths:
      - "devcontainer/**"
      - ".github/workflows/devcontainer.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: devcontainer

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Build and push the image
        run: devcontainer build --image-name ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }} --workspace-folder devcontainer --cache-from type=gha --cache-to type=gha,mode=max --push
